"""rename address

Revision ID: 340796991013
Revises: 7d6605ed4422
Create Date: 2025-03-25 11:40:30.871767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340796991013'
down_revision = '7d6605ed4422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
